[package]
description = "Compiler driver for the Covenant smart contract language"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["compiler", "driver", "smart-contracts", "covenant"]
categories = ["development-tools"]
name = "covenant-driver"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
covenant-lexer = { path = "../covenant-lexer", version = "0.9.2" }
covenant-parser = { path = "../covenant-parser", version = "0.9.2" }
covenant-resolver = { path = "../covenant-resolver", version = "0.9.2" }
covenant-types = { path = "../covenant-types", version = "0.9.2" }
covenant-privacy = { path = "../covenant-privacy", version = "0.9.2" }
covenant-ir = { path = "../covenant-ir", version = "0.9.2" }
covenant-opt = { path = "../covenant-opt", version = "0.9.2" }
covenant-evm-backend = { path = "../covenant-evm-backend", version = "0.9.2" }
covenant-aster-backend = { path = "../covenant-aster-backend", version = "0.9.2" }
covenant-wasm-backend = { path = "../covenant-wasm-backend", version = "0.9.2" }
covenant-circuits = { path = "../covenant-circuits", version = "0.9.2" }
covenant-stdlib = { path = "../covenant-stdlib", version = "0.9.2" }
covenant-manifest = { path = "../covenant-manifest", version = "0.9.2" }
covenant-diag = { path = "../covenant-diag", version = "0.9.2" }
thiserror = { workspace = true }
