#!/usr/bin/env bash
#
# End-to-end proof that compiler output runs on a real EVM.
#
# Until now the only on-chain check was a direct `cast send` to a deployed
# helper, which proves the helper works, not that a contract the compiler
# generates deploys and behaves. This closes that gap for the portable subset:
# it compiles a token, deploys the emitted bytecode to a local anvil, and
# exercises the ERC-20 surface, asserting on-chain state at each step.
#
# No key of yours is involved. anvil ships deterministic dev accounts whose
# keys are public and hold nothing; account 0 below is one of them.
#
# Usage:  scripts/e2e-anvil.sh
# Needs:  forge, anvil, cast (Foundry) on PATH, and a built release compiler.
# Exits:  0 if every assertion passes, non-zero on the first failure.

set -euo pipefail

PY="$(command -v python3 || command -v python)"

PORT="${ANVIL_PORT:-8546}"
RPC="http://127.0.0.1:${PORT}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"

# anvil dev account 0. Public, deterministic, unfunded on any real chain.
PK="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
DEPLOYER="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
BOB="0x70997970C51812dc3A010C7d01b50e0d17dc79C8"

COVENANT="${COVENANT:-}"
if [ -z "$COVENANT" ]; then
  for c in "$ROOT/target/release/covenant" "$ROOT/target/release/covenant.exe"; do
    [ -x "$c" ] && COVENANT="$c" && break
  done
fi

say()  { printf '\n== %s ==\n' "$*"; }
pass() { printf '  ok   %s\n' "$*"; }
fail() { printf '  FAIL %s\n' "$*" >&2; exit 1; }
eq()   { [ "$1" = "$2" ] && pass "$3 = $1" || fail "$3: got $1, expected $2"; }

command -v anvil >/dev/null || { echo "anvil not found (https://getfoundry.sh)"; exit 2; }
command -v cast  >/dev/null || { echo "cast not found";  exit 2; }
[ -n "$COVENANT" ] && [ -x "$COVENANT" ] || {
  echo "no release compiler; run: cargo build --release --bin covenant"; exit 2;
}

ANVIL_PID=""
cleanup() {
  [ -n "$ANVIL_PID" ] && kill "$ANVIL_PID" 2>/dev/null || true
  rm -rf "$WORK"
}
trap cleanup EXIT

say "Starting anvil on port ${PORT}"
anvil --port "$PORT" --silent &
ANVIL_PID=$!
for _ in $(seq 1 30); do
  cast chain-id --rpc-url "$RPC" >/dev/null 2>&1 && break
  sleep 1
done
cast chain-id --rpc-url "$RPC" >/dev/null 2>&1 || fail "anvil did not come up"
pass "anvil up, chainId $(cast chain-id --rpc-url "$RPC")"

say "Compiling a token with the release compiler"
cat > "$WORK/coin.cov" <<'COV'
token DemoCoin {
    symbol:   "DEMO"
    name:     "Demo Coin"
    decimals: 18
    supply:   1_000_000 to deployer
}
COV
"$COVENANT" build "$WORK/coin.cov" --out "$WORK/out" >/dev/null
BIN_FILE="$WORK/out/DemoCoin.bin"
[ -f "$BIN_FILE" ] || fail "compiler produced no bytecode"
pass "compiled, $(( $(wc -c < "$BIN_FILE") / 2 )) bytes of deploy bytecode"

say "Deploying the generated bytecode"
BIN="0x$(tr -d '\n\r ' < "$BIN_FILE" | sed 's/^0x//')"
RECEIPT="$(cast send --rpc-url "$RPC" --private-key "$PK" --json --create "$BIN")"
ADDR="$(echo "$RECEIPT" | "$PY" -c 'import sys,json;print(json.load(sys.stdin)["contractAddress"])')"
[ -n "$ADDR" ] || fail "no contractAddress in receipt"
[ "$(cast code "$ADDR" --rpc-url "$RPC")" != "0x" ] || fail "no code at $ADDR after deploy"
pass "deployed to $ADDR with runtime code present"

say "Reading the synthesized ERC-20 surface"
eq "$(cast call "$ADDR" 'name()(string)'   --rpc-url "$RPC")" '"Demo Coin"' "name()"
eq "$(cast call "$ADDR" 'symbol()(string)' --rpc-url "$RPC")" '"DEMO"'      "symbol()"
sup="$(cast call "$ADDR" 'totalSupply()(uint256)' --rpc-url "$RPC" | grep -oE '^[0-9]+')"
eq "$sup" "1000000" "totalSupply()"
dep="$(cast call "$ADDR" 'balanceOf(address)(uint256)' "$DEPLOYER" --rpc-url "$RPC" | grep -oE '^[0-9]+')"
eq "$dep" "1000000" "balanceOf(deployer)"

say "Exercising a transfer"
tx="$(cast send "$ADDR" 'transfer(address,uint256)' "$BOB" 250000 --rpc-url "$RPC" --private-key "$PK" --json)"
eq "$(echo "$tx" | "$PY" -c 'import sys,json;print(json.load(sys.stdin)["status"])')" "0x1" "transfer status"
dep2="$(cast call "$ADDR" 'balanceOf(address)(uint256)' "$DEPLOYER" --rpc-url "$RPC" | grep -oE '^[0-9]+')"
bob2="$(cast call "$ADDR" 'balanceOf(address)(uint256)' "$BOB" --rpc-url "$RPC" | grep -oE '^[0-9]+')"
tot2="$(cast call "$ADDR" 'totalSupply()(uint256)' --rpc-url "$RPC" | grep -oE '^[0-9]+')"
eq "$dep2" "750000" "balanceOf(deployer) after transfer"
eq "$bob2" "250000" "balanceOf(bob) after transfer"
[ "$(( dep2 + bob2 ))" -eq "$tot2" ] && pass "conservation: $dep2 + $bob2 == $tot2" \
  || fail "conservation broken: $dep2 + $bob2 != $tot2"

say "Negative control: transfer beyond balance must revert"
if cast send "$ADDR" 'transfer(address,uint256)' "$BOB" 999999999 \
     --rpc-url "$RPC" --private-key "$PK" >/dev/null 2>&1; then
  fail "an over-balance transfer succeeded, so the balance check is not enforced"
else
  pass "over-balance transfer reverted"
fi

say "All assertions passed"
