[package]
description = "Name resolution pass for the Covenant compiler"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["compiler", "resolver", "smart-contracts", "covenant"]
categories = ["development-tools"]
name = "covenant-resolver"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
covenant-parser = { path = "../covenant-parser", version = "0.9.2" }
covenant-diag = { path = "../covenant-diag", version = "0.9.2" }
thiserror = { workspace = true }

[dev-dependencies]
covenant-lexer = { path = "../covenant-lexer", version = "0.9.2" }
